Yoshubs/Forever-Engine-Legacy

Project.xml, source/Main.hx, source/gameFolder/gameObjects/userInterface/ClassHUD.hx, source/gameFolder/gameObjects/userInterface/menu/MenuItem.hx, source/gameFolder/meta/data/font/Alphabet.hx, source/gameFolder/meta/state/FreeplayState.hx, source/gameFolder/meta/state/MainMenuState.hx, source/gameFolder/meta/state/PlayState.hx, source/gameFolder/meta/state/StoryMenuState.hx
Issue #3 
HTML5 used to be not work.
Now its kinda work! Amazing!
_Basically i just made HTML5 run at 60 fps to prevent weird bugs.
And fixed the problems that come with that._
=> Fixing HTML5

source/Paths.hx, source/gameFolder/gameObjects/Stage.hx, source/gameFolder/meta/CoolUtil.hx
I used a little bit of magic to fix #12.
=> Song names can now have spaces or dashes.

source/Init.hx, source/gameFolder/meta/data/font/Alphabet.hx, source/gameFolder/meta/state/PlayState.hx
This fixes:
- Inconsistent lerp speed
- System cursor instead of Flixel cursor
=> Some visual fixes

source/gameFolder/meta/state/TitleState.hx
oh yeah Shubs you could give me push access :wink:
=> Remove useless timer on TitleState

source/gameFolder/meta/MusicBeat.hx, source/gameFolder/meta/state/PlayState.hx
This fixes the countdown timer, notably present after the "Go!" part.
=> Countdown fix (and some debugging goodies)

source/gameFolder/gameObjects/Character.hx, source/gameFolder/gameObjects/Stage.hx, source/gameFolder/meta/state/PlayState.hx, source/gameFolder/meta/state/menus/FreeplayState.hx
- Free play menu text in the top right scales properly (doesn't look weird anymore because I'm sorry but it did)
- Added idlePost, just a way to lead into another animation after the idle animation is finished. Useful for hair waving in week 4 for example but there's plenty of other uses
- Fading street lights in the Philly city area
- Character animations work every other beat now unless you enabled 'quickDancer', which makes them animate per-beat. This is to match how the characters in week 7 animate. (I didn't apply this to the background dancers but it could just as well be put on there to make them bob their heads too)
- Uhhhh added swag
=> Small adjustments to a few things

Project.xml, source/Main.hx
This should get the crash dialogue up and running.
Features missing on this PR:
- Un-hardcoded funny messages
- Un-hardcoded banners
=> Partial crash dialogue implementation

.gitignore, docs/Makefile, docs/about/introduction.rst, docs/conf.py, docs/index.rst, docs/make.bat, docs/tutorials/1-getting-started.rst
This should trigger the Read The Docs build system for the first time (actually the second but who cares)
=> Read The Docs setup

source/gameFolder/gameObjects/Note.hx
made it so quants no longer get ruined by offsets
=> fixed quants being broken w/ offsets

source/gameFolder/meta/data/Conductor.hx, source/gameFolder/meta/data/Section.hx, source/gameFolder/meta/data/Song.hx, source/gameFolder/meta/state/charting/ChartingState.hx, source/gameFolder/meta/state/charting/OriginalChartingState.hx
because you were scared to do so :troll_4k_troll:
Also includes experimental custom measure support
=> trying to make a pr part 2: making bpms floats

source/gameFolder/meta/state/menus/FreeplayState.hx
NO MORE ~~FRIDAY NIGHT FUNKIN~~ CACHING!!!
=> Freeplay thread loading

source/gameFolder/meta/state/menus/FreeplayState.hx
Never program in a rush, kids!
=> BUG BUG BUG BUG BUG (Freeplay thread cont'd)

.vscode/settings.json, assets/shaders/vhs.frag, source/flixel/graphics/tile/FlxGraphicsShader.hx, source/gameFolder/meta/state/PlayState.hx, source/openfl/display/GraphicsShader.hx, source/openfl/display/Shader.hx, source/openfl/filters/ColorMatrixFilter.hx
Ended up overriding some OpenFL and HaxeFlixel source code for this one. This is a highly experimental code and crashes are bound to happen, but it's a start.
=> Runtime shader parsing support for modcharts

source/gameFolder/meta/shaders/PerspectiveShader.hx, source/gameFolder/meta/state/PlayState.hx
=> FIX CRASH IN PLAYSTATE

source/gameFolder/meta/shaders/PerspectiveShader.hx, source/gameFolder/meta/state/PlayState.hx
=> revert hayas thingies 1

source/gameObjects/userInterface/notes/Note.hx, source/meta/state/PlayState.hx
i think this fix bpm changes n shit idk man
=> maybe fix bpm changes?? idk

source/meta/state/menus/FreeplayState.hx
forgor to use mutex 💀 hopefully this fixes that pesky SoundTransform error!
=> Fix Freeplay Song Thread sync problem

source/Init.hx, source/meta/state/menus/OptionsMenuState.hx
the game will remember your last volume when you close it
auto pause was unused for a while, so I made it work
=> Automatically Save Game's Last Volume + Auto Pause Option

source/gameObjects/userInterface/ClassHUD.hx
=> cleaning up ClassHUD

Project.xml, source/Main.hx, source/gameObjects/userInterface/notes/Note.hx, source/meta/Overlay.hx, source/meta/data/ChartLoader.hx, source/meta/data/dependency/Discord.hx, source/meta/state/CustomTitlescreen.hx, source/meta/state/PlayState.hx, source/meta/state/TitleState.hx, source/meta/state/charting/OriginalChartingState.hx, source/meta/state/menus/FreeplayState.hx, source/meta/state/menus/MainMenuState.hx, source/meta/state/menus/OptionsMenuState.hx, source/meta/state/menus/StoryMenuState.hx, source/meta/subState/GameOverSubstate.hx, source/meta/subState/OptionsSubstate.hx, source/meta/subState/PauseSubState.hx
https://user-images.githubusercontent.com/45212377/178119839-6f88fbae-6ca8-4083-a23e-42a92b43e74c.mp4
-- what's new
* Game now Tracks Deaths (you can see how many times you've died on a song by pressing ENTER)
* OG Charting State now switches character icons correctly
* Deleting a Note shouldn't delete the other player's note
* OG Charting State now has hitsounds for both player 1 and player 2, making charting a little bit easier (thx shadowmario for this one, I couldn't figure it out at first)
* Current Beat and Current Step are now shown
* Added Support for Compiling with `lime test neko`, you can basically compile the game as fast as html5 now, with missing features such as offsets not being present, state debug info and framerate caps being missing and worse performance, it's a …
=> Game now Tracks Deaths, OriginalChartingState improvements, Neko Platform Support

Project.xml, source/Main.hx, source/Paths.hx, source/gameObjects/userInterface/HealthIcon.hx
This can freeze the game if the icon isn't found so this fixes it
And a fix in project.xml
=> A very small fix

source/meta/subState/OptionsSubstate.hx
sorry for bringing too many small fixes in a short amount of time aaaaaa
anyway uhh this fixes a bug where binding UI Keys would return null
https://user-images.githubusercontent.com/45212377/178128701-90ef60bd-381d-4dfa-9579-9a6e2827a9ae.mp4
=> Fix UI Controls crashing the game

assets/assetModifiersList.txt, source/meta/data/Song.hx, source/meta/state/PlayState.hx, source/meta/state/charting/OriginalChartingState.hx
https://user-images.githubusercontent.com/45212377/178350220-1cd57f29-6fa3-490c-9972-accca2bf8d57.mp4
added custom asset modifiers (skins, if you will) on chart editor, along with some other improvements to it
=> Asset Modifiers Changeable through Chart Editor + OG Charter Fixes

source/meta/Overlay.hx
same as [this](https://github.com/Yoshubs/FNF-Forever-Engine/pull/15), but for Legacy
=> Fix Memory Peak treating anything greater than 999.99MB as lower

Project.xml, source/gameObjects/userInterface/ClassHUD.hx, source/meta/state/menus/MainMenuState.hx
* Renamed the app title,
* Renamed the .exe file,
* Renamed ``packageName`` and ``package`` from ``com.yoshubs.foreverengine`` to ``com.yoshubs.foreverenginelegacy``,
* Changed the version from FNF's version to the actual engine version itself.
* Formatted the file.
* Rename ``Forever Engine`` and ``FOREVER ENGINE`` to ``Forever Engine Legacy`` and ``FOREVER ENGINE LEGACY``.
Did this for the sole purpose of making a difference between Legacy and the Rewrite of this engine.
=> Small adjustments

README.md, docs/COMPILE-HELP.md
* Rewrites the entire README,
* Separates the compiling guide in the legacy README to a new file called ``COMPILE-HELP.md`` in ``docs/``.
=> README Rewrite

source/meta/state/PlayState.hx
pretty much just what the title says. The pr pauses every timer and tween not just the start-timer.
=> Pause all timers/tweens

source/Init.hx, source/Main.hx, source/gameObjects/userInterface/ClassHUD.hx, source/gameObjects/userInterface/DialogueBox.hx, source/gameObjects/userInterface/HealthIcon.hx, source/meta/data/Timings.hx, source/meta/data/font/Alphabet.hx, source/meta/state/PlayState.hx, source/meta/state/charting/ChartingState.hx, source/meta/state/menus/OptionsMenuState.hx, source/meta/subState/OptionsSubstate.hx, source/meta/subState/PauseSubState.hx
read commit description for details
a few explanations before merging:
- Changed "FOREVER ENGINE" to "F.E." on the Center Mark so it isn't as big of a text field;
- the bot mark is labeled "AUTOPLAY" for it to be consistent with the boolean name, which is `boyfriendStrums.autoplay`, you can later change that if you wish
=> small changes and fixes
